version: '3.8'

services:
  database:
    container_name: cilist-db
    image: ravennaras/cilist:db-v1

  backend:
    image: ravennaras/cilist:backend-v1
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=database
      - DATABASE_PORT=3306

  frontend:
    image: ravennaras/cilist:frontend-v1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://ec2-54-158-109-62.compute-1.amazonaws.com:5000